export const ROUTES = {
    MAIN: '/main',
    FEEDBACKS: '/feedbacks',
    AUTH: '/auth',
    REGISTRATION: '/auth/registration',
    ERROR_LOGIN: '/result/error-login',
    SUCCESS_REGISTRATION: '/result/success',
    ERROR_USER_EXIST: '/result/error-user-exist',
    RESULT_ERROR: '/result/error',
    CONFIRM_EMAIL: '/auth/confirm-email',
    ERROR_CHECK_EMAIL_NO_EXIST: '/result/error-check-email-no-exist',
    ERROR_CHECK_EMAIL: '/result/error-check-email',
    CHANGE_PASSWORD: '/auth/change-password',
    SUCCESS_CHANGE_PASSWORD: '/result/success-change-password',
    ERROR_CHANGE_PASSWORD: '/result/error-change-password',
    CALENDAR: '/calendar',
    PROFILE: '/profile',
    SETTINGS: '/settings',
    TRAININGS: '/trainings',
    ACHIEVEMENTS: '/achievements',
  };